apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config
  namespace: freqtrade
data:
  config.json: |
    {
        "$schema": "https://schema.freqtrade.io/schema.json",
        "max_open_trades": 8,
        "stake_currency": "USDT",
        "stake_amount": "unlimited",
        "tradable_balance_ratio": 0.99,
        "fiat_display_currency": "USD",
        "dry_run": false,
        "dry_run_wallet": 600,
        "cancel_open_orders_on_exit": false,
        "trading_mode": "spot",
        "margin_mode": "",
        "unfilledtimeout": {
            "entry": 10,
            "exit": 10,
            "exit_timeout_count": 0,
            "unit": "minutes"
        },
        "entry_pricing": {
            "price_side": "same",
            "use_order_book": true,
            "order_book_top": 1,
            "price_last_balance": 0.0,
            "check_depth_of_market": {
                "enabled": false,
                "bids_to_ask_delta": 1
            }
        },
        "exit_pricing":{
            "price_side": "same",
            "use_order_book": true,
            "order_book_top": 1
        },
        "exchange": {
            "name": "binance",
            "key": "",
            "secret": "",
            "ccxt_config": {"enableRateLimit": true},
            "ccxt_async_config": {
                "enableRateLimit": true,
                "rateLimit": 3100
            },    
            "pair_whitelist": [
                "BCH/USDT",
                "LTC/USDT",
                "NEAR/USDT",
                "APT/USDT",
                "ICP/USDT",
                "ETC/USDT",
                "RENDER/USDT",
                "VET/USDT",
                "ARB/USDT",
                "FIL/USDT",
                "ATOM/USDT",
                "STX/USDT",
                "THETA/USDT",
                "SEI/USDT",
                "WLD/USDT",
                "OP/USDT",
                "TIA/USDT",
                "GRT/USDT",
                "PYTH/USDT",
                "DOGE/USDT",
                "TRX/USDT",
                "AVAX/USDT",
                "TON/USDT",
                "DOT/USDT",
                "XLM/USDT",
                "SHELL/USDT",
                "API3/USDT",
                "XRP/USDT",
                "BTC/USDT",
                "ETH/USDT",
                "EDU/USDT",
                "GUN/USDT",
                "EOS/USDT",
                "VIRTUAL/USDT",
                "PIXEL/USDT",            
                "TAO/USDT",
                "S/USDT",
                "SUI/USDT",
                "SOL/USDT",
                "RSR/USDT",
                "QKC/USDT",            
                "POND/USDT",
                "PARTI/USDT",
                "LAYER/USDT",
                "GAS/USDT",
                "FIDA/USDT",
                "ENA/USDT",
                "CATI/USDT",
                "BMT/USDT",            
                "AMP/USDT",
                "AGLD/USDT",
                "ADA/USDT",
                "HIVE/USDT",
                "HBAR/USDT",
                "LINK/USDT"        
            ],
            "pair_blacklist": [
                "BNB/.*"
            ]
        },
        "pairlists": [
            {
                "method": "StaticPairList",
                "number_assets": 62,
                "sort_key": "quoteVolume",
                "min_value": 0,
                "refresh_period": 60
            }
        ],
        "telegram": {
            "enabled": true,
            "token": "",
            "chat_id": ""
        },
        "api_server": {
            "enabled": true,
            "listen_ip_address": "0.0.0.0",
            "listen_port": 8080,
            "verbosity": "error",
            "enable_openapi": false,
            "jwt_secret_key": "",
            "ws_token": "",
            "CORS_origins": [],
            "username": "",
            "password": ""
        },
        "bot_name": "freqtrade",
        "initial_state": "running",
        "force_entry_enable": false,
        "internals": {
            "process_throttle_secs": 5
        }
    } 