apiVersion: apps/v1
kind: Deployment
metadata:
  name: ase-stock-api
  namespace: ase-stocks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ase-stock-api
  template:
    metadata:
      labels:
        app: ase-stock-api
    spec:
      nodeSelector:
        node.kubernetes.io/environment: "production"
      containers:
      - name: ase-stock-api
        image: aabutouq/ase-stock-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: aabutouq-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ase-stock-api
  namespace: ase-stocks
spec:
  selector:
    app: ase-stock-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
