apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ase-stock-api
  namespace: ase-stocks
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - stocks.homebytes.space
    secretName: stocks-tls-secret
  rules:
  - host: stocks.homebytes.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ase-stock-api
            port:
              number: 80